owner: Pradumnasaraf 
repo: Monitoring 

sites:
  - name: Pradumna's Website
    url: https://pradumnasaraf.dev
  - name: Pradumna's Website (XYZ)
    url: https://pradumnasaraf.xyz
  - name: Pradumna's Newsletter
    url: https://newsletter.pradumnasaraf.dev
  - name: Pradumna's Blog (Hashnode)
    url: https://blog.pradumnasaraf.dev  
  - name: Pradumna's Photography
    url: https://camera.pradumnasaraf.dev
  - name: Open Source With Pradumna
    url: https://os.pradumnasaraf.dev
  - name: DevOps 
    url: https://devops.pradumnasaraf.dev
  - name: Snippets 
    url: https://snippets.pradumnasaraf.dev
  - name: Open API
    url: https://opensourceapi.vercel.app
  - name: Candy Go Package
    url: https://pkg.go.dev/github.com/Pradumnasaraf/candy
  - name: GenCLI Go Package
    url: https://pkg.go.dev/github.com/Pradumnasaraf/gencli
  - name: BioLink
    url: https://links.pradumnasaraf.dev
  - name: rebase media website
    url: https://rebasemedia.com
  - name: rebase media website (XYZ)
    url: https://rebasemedia.xyz
status-website:
  baseUrl: /Monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pradumna's Monitoring page
  introTitle: Monitoring of Pradumna apps and site.
  introMessage: Monitoring....
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Twitter
      href: https://twitter.com/pradumna_saraf
